import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Head from "next/head";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-display bg-background">
        <Head>
          <meta name="viewport" content="viewport-fit=cover" />
        </Head>
        <div className="isolate bg-accent px-6 py-12 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <Header />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
